### ISSUE TITLE
Node doesn't appear if `enhanced` is not selected

### ISSUE THREAD

**Issue by cyanCYMK** [predixdesignsystem/px-timeline#5]
## Expected behavior and actual behavior:
Example from docs:
<img width="986" alt="screen shot 2017-08-10 at 10 58 54 am" src="https://user-images.githubusercontent.com/7728581/29184408-f0e1a0c0-7dba-11e7-95b0-22a183bf8e99.png">

Using `px-timeline` as such within AngularJS:
```
        <px-timeline
            timeline-data="{{$ctrl.flowInstances}}"
            date-format="MMM D, YYYY HH:MM"
            show-node-content>
        </px-timeline>
```
Where $ctrl.flowInstances is formatted like
```
[
    {
        metaData: {
            editedDate: instance.startTime // number
        },
        content: {
            title: instance.status, // string
            body: [{}],
            bodyType: 'text'
        }
    }
]
```
Expected behavior to look like example in docs with node displayed without a chevron

## Steps to reproduce the problem:
```
<px-timeline
    timeline-data="[{"metaData":{"editedDate":1502146813023},"content":{"title":"FINISHED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502147339224},"content":{"title":"KILLED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502147955557},"content":{"title":"KILLED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502147993605},"content":{"title":"KILLED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502148050322},"content":{"title":"FINISHED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502148606027},"content":{"title":"KILLED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502148633087},"content":{"title":"KILLED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502148663991},"content":{"title":"KILLED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502148692635},"content":{"title":"KILLED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502148716951},"content":{"title":"KILLED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502148743563},"content":{"title":"KILLED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502153998107},"content":{"title":"FINISHED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502155102534},"content":{"title":"KILLED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502155326799},"content":{"title":"KILLED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502155357632},"content":{"title":"FINISHED","body":[{}],"bodyType":"text"}}]"
    date-format="MMM D, YYYY HH:MM"
    show-node-content>
</px-timeline>
```

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
├─┬ px-timeline#1.0.5
Google Chrome Version 60.0.3112.90 (Official Build) (64-bit)
OSX El Capitan Version 10.11.6 (15G1611)

## Screenshots (_optional, but very helpful_):
<img width="521" alt="screen shot 2017-08-10 at 10 53 08 am" src="https://user-images.githubusercontent.com/7728581/29184162-216830b6-7dba-11e7-86ca-914cd61d82be.png">

**Comment by randyaskin** [comment]
Thank you for the level of detail. I'll have to look into why the CodePen is broken.

I pasted the sample data you provided into our demo page in my local environment and it displayed as expected (with the circles/lines on the left, not like your screenshot). So the data isn't the issue. My next guess would be the Angular binding, but the data itself seems to be displaying fine, so that's unlikely too. 

It could just be a timing issue... what happens if you turn enhanced on and then off again in inspector? e.g. highlight the px-timeline component and run `$0.set('enhanced', true); $0.set('enhanced', false);` in console - that should trigger two re-draws of the component and let us know if it's a timing issue. Also would be helpful if you use inspectElement in the area where we expect the circles to appear and see if it's a case of actual missing DOM or just display:none or something.

Just to double-check, you're not doing anything with css variables, right? `--px-timeline-border-color: white` (or transparent) would result in the view you included in your screencap.

**Comment by AdmiralsGE** [comment]
We re facing related Issues, here are few screenshot..

1)	Px-timeline arrow icon still appears when there is no data inside the node with enahanced attribute
2)	When enhanced is not using the round icons are disappearing

Would appreciate if we get any update or information we are missing.. 

![arrow down](https://user-images.githubusercontent.com/32395033/31023354-91aa15f8-a509-11e7-8002-08ca1ba82d03.jpg)
![arrow up](https://user-images.githubusercontent.com/32395033/31023355-91ae37fa-a509-11e7-9b81-6cb53f70bce7.PNG)

**Comment by e-kag** [comment]
@cyanCYMK I failed to reproduce this issue with your configuration:
`<px-timeline
    timeline-data="[{"metaData":{"editedDate":1502146813023},"content":{"title":"FINISHED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502147339224},"content":{"title":"KILLED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502147955557},"content":{"title":"KILLED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502147993605},"content":{"title":"KILLED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502148050322},"content":{"title":"FINISHED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502148606027},"content":{"title":"KILLED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502148633087},"content":{"title":"KILLED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502148663991},"content":{"title":"KILLED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502148692635},"content":{"title":"KILLED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502148716951},"content":{"title":"KILLED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502148743563},"content":{"title":"KILLED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502153998107},"content":{"title":"FINISHED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502155102534},"content":{"title":"KILLED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502155326799},"content":{"title":"KILLED","body":[{}],"bodyType":"text"}},{"metaData":{"editedDate":1502155357632},"content":{"title":"FINISHED","body":[{}],"bodyType":"text"}}]"
    date-format="MMM D, YYYY HH:MM"
    show-node-content>
</px-timeline>`

Are you you still facing this issue?

@AdmiralsGE how is the `body` attribute defined? If it is defined as above (`"body":[{}]`), then the reason the chevron is appearing is because you have included an item (ie. `{}`) in the body, but it happens to be an empty item. If the body is empty, then define as `"body":[]` or simply exclude from attributes.
With that said, you will likely face this issue: https://github.com/predixdesignsystem/px-timeline/issues/10 (which includes the icon trouble you have mentioned). I am working on it at the moment.
